// Code generated by a fake tool. DO NOT EDIT.

package a

import "reflect"

// A program writes this file, so a report here has no reader who can
// act on it.
func GeneratedDescribe(v any) string {
	return reflect.TypeOf(v).String()
}
