// Code generated by a fake tool. DO NOT EDIT.

package a

import "os"

// Nobody edits a generated file to add a justification, so a report
// here has no reader who can act on it. This file carries no want
// comment, and a diagnostic in it fails the suite.

func GeneratedPanic() {
	panic("the generator wrote this line")
}

func GeneratedExit(code int) {
	os.Exit(code)
}
