// This file holds the file tests that the rules apply. A rule reads
// the shape of hand-written code, and the tests below answer which
// file it reads. One implementation cannot drift from itself.

package signature

import (
	"go/ast"
	"go/token"
	"strings"

	"golang.org/x/tools/go/analysis"

	"github.com/JacobJNilsson/anti-slop-go/internal/pathmatch"
)

// generatedMarkers holds the marker text of a generated file. The test
// lowercases the header first, so each value here is lowercase.
//
// golangci-lint holds the same four values in the lax mode of its
// generated-file matcher. The module adopts them with no change, so the
// two tools read the same marker text. The window is another question,
// and 003 states where the two differ.
var generatedMarkers = []string{
	"code generated",     // the canonical marker, https://go.dev/s/generatedcode
	"do not edit",        // cgo -godefs, and other generators with no canonical header
	"autogenerated file", // easyjson
	// Swagger Codegen, in a block comment. The star is the gutter of
	// that comment. The space at the end sits before the version, and a
	// change that drops it widens the marker.
	"* generated by: swagger codegen ",
}

// GeneratedFiles returns the generated-file test for one pass. The test
// answers true for a position in a file whose header carries a
// generated-file marker. isGenerated states the accepted header forms.
//
// Every rule needs this test, and a rule without a marker takes it
// alone. A rule states the shape of hand-written code, so a report
// against a file that a program writes has no reader who can act on it.
//
// The set behind the test holds each token.File itself, not its name. A
// //line directive changes the name that token.Position reports, so a
// comparison of names can exempt the wrong file in both directions.
func GeneratedFiles(pass *analysis.Pass) func(pos token.Pos) bool {
	files := make(map[*token.File]bool)
	for _, file := range pass.Files {
		if isGenerated(file) {
			files[pass.Fset.File(file.FileStart)] = true
		}
	}
	return func(pos token.Pos) bool { return files[pass.Fset.File(pos)] }
}

// isGenerated reports whether the header of a file carries a
// generated-file marker.
//
// The first test is ast.IsGenerated. It accepts the canonical
// "Code generated ... DO NOT EDIT." header alone. go/ast owns that
// form, and the module states it once through go/ast.
//
// The marker loop below accepts the canonical text as well, so
// ast.IsGenerated exempts no file on its own today. The call stays
// because go/ast owns the canonical form. A later change to the marker
// strings below then cannot drop that form by accident.
//
// The marker loop accepts the wider marker set that golangci-lint calls
// its lax mode. Generators exist that write no canonical header. An
// in-house identifier generator writes "Generated file, do not edit.".
// That sentence carries the same evidence as the canonical one.
//
// Both tests read one window: the comment text above the package
// clause. The module reads no line below that clause. A "do not edit"
// comment beside one statement says nothing about the file. A
// whole-file scan would drop every report of that file.
func isGenerated(file *ast.File) bool {
	if ast.IsGenerated(file) {
		return true
	}

	header := strings.ToLower(headerText(file))
	for _, marker := range generatedMarkers {
		if strings.Contains(header, marker) {
			return true
		}
	}

	return false
}

// headerText returns the comment text above the package clause of a
// file. ast.CommentGroup.Text removes the comment delimiters and the
// build directives, so the result holds the words of the header alone.
//
// A comment group that reaches past the package clause ends the window,
// and the groups of a file arrive in the order of their positions.
func headerText(file *ast.File) string {
	var groups []string
	for _, group := range file.Comments {
		if group.End() > file.Package {
			break
		}
		groups = append(groups, strings.TrimSpace(group.Text()))
	}

	return strings.Join(groups, "\n")
}

// IsTestFile reports whether a file is a test file by its name. The
// name is the test the go tool applies.
//
// The name of the package answers another question. It separates the
// external test package from the test files that sit in the package
// under test. A rule that reads test code reads both.
//
// A project also holds test code that carries no such name, and
// TestFiles below states the wider test that the rules apply.
func IsTestFile(file *token.File) bool {
	return strings.HasSuffix(file.Name(), "_test.go")
}

// IsTestPackage reports whether the patterns name a package that
// serves tests. 003 states the pattern syntax.
//
// The external test package of a package carries the path of that
// package with "_test" at the end. Both hold the code of one package,
// so the test drops that suffix and one entry covers both.
func IsTestPackage(patterns []string, path string) bool {
	return pathmatch.Any(patterns, strings.TrimSuffix(path, "_test"))
}

// TestFiles returns the test that decides whether a position of one
// pass sits in a test file. The test answers true for a position in a
// file whose name ends in "_test.go". It answers true for every
// position of a package that the patterns name.
//
// A package can serve tests and carry no such file name. A shared
// suite that a TestMain function starts is one such package. The file
// name test alone makes its files production code, so the rules that
// read test files report the wrong thing there. The test-packages
// setting names the package, and 002 states which packages count.
//
// Five rules read this test, so the module holds one answer for one
// file. 003 states the setting and the five flags.
func TestFiles(pass *analysis.Pass, testPackages []string) func(pos token.Pos) bool {
	if IsTestPackage(testPackages, pass.Pkg.Path()) {
		return func(token.Pos) bool { return true }
	}

	return func(pos token.Pos) bool {
		file := pass.Fset.File(pos)

		return file != nil && IsTestFile(file)
	}
}
