// This file holds the file tests that every rule applies. A rule reads
// the shape of hand-written code, and the two tests below answer which
// file it reads. One implementation cannot drift from itself.

package signature

import (
	"go/ast"
	"go/token"
	"strings"

	"golang.org/x/tools/go/analysis"
)

// generatedMarkers holds the marker text of a generated file. The test
// lowercases the header first, so each value here is lowercase.
//
// golangci-lint holds the same four values in the lax mode of its
// generated-file matcher. The module adopts them with no change, so the
// two tools read the same marker text. The window is another question,
// and 003 states where the two differ.
var generatedMarkers = []string{
	"code generated",     // the canonical marker, https://go.dev/s/generatedcode
	"do not edit",        // cgo -godefs, and other generators with no canonical header
	"autogenerated file", // easyjson
	// Swagger Codegen, in a block comment. The star is the gutter of
	// that comment. The space at the end sits before the version, and a
	// change that drops it widens the marker.
	"* generated by: swagger codegen ",
}

// GeneratedFiles returns the generated-file test for one pass. The test
// answers true for a position in a file whose header carries a
// generated-file marker. isGenerated states the accepted header forms.
//
// Every rule needs this test, and a rule without a marker takes it
// alone. A rule states the shape of hand-written code, so a report
// against a file that a program writes has no reader who can act on it.
//
// The set behind the test holds each token.File itself, not its name. A
// //line directive changes the name that token.Position reports, so a
// comparison of names can exempt the wrong file in both directions.
func GeneratedFiles(pass *analysis.Pass) func(pos token.Pos) bool {
	files := make(map[*token.File]bool)
	for _, file := range pass.Files {
		if isGenerated(file) {
			files[pass.Fset.File(file.FileStart)] = true
		}
	}
	return func(pos token.Pos) bool { return files[pass.Fset.File(pos)] }
}

// isGenerated reports whether the header of a file carries a
// generated-file marker.
//
// The first test is ast.IsGenerated. It accepts the canonical
// "Code generated ... DO NOT EDIT." header alone. go/ast owns that
// form, and the module states it once through go/ast.
//
// The marker loop below accepts the canonical text as well, so
// ast.IsGenerated exempts no file on its own today. The call stays
// because go/ast owns the canonical form. A later change to the marker
// strings below then cannot drop that form by accident.
//
// The marker loop accepts the wider marker set that golangci-lint calls
// its lax mode. Generators exist that write no canonical header. An
// in-house identifier generator writes "Generated file, do not edit.".
// That sentence carries the same evidence as the canonical one.
//
// Both tests read one window: the comment text above the package
// clause. The module reads no line below that clause. A "do not edit"
// comment beside one statement says nothing about the file. A
// whole-file scan would drop every report of that file.
func isGenerated(file *ast.File) bool {
	if ast.IsGenerated(file) {
		return true
	}

	header := strings.ToLower(headerText(file))
	for _, marker := range generatedMarkers {
		if strings.Contains(header, marker) {
			return true
		}
	}

	return false
}

// headerText returns the comment text above the package clause of a
// file. ast.CommentGroup.Text removes the comment delimiters and the
// build directives, so the result holds the words of the header alone.
//
// A comment group that reaches past the package clause ends the window,
// and the groups of a file arrive in the order of their positions.
func headerText(file *ast.File) string {
	var groups []string
	for _, group := range file.Comments {
		if group.End() > file.Package {
			break
		}
		groups = append(groups, strings.TrimSpace(group.Text()))
	}

	return strings.Join(groups, "\n")
}

// IsTestFile reports whether a file is a test file. The name of the
// file is the whole test, which is the test the go tool applies.
//
// The name of the package answers another question. It separates the
// external test package from the test files that sit in the package
// under test. A rule that reads test code reads both.
func IsTestFile(file *token.File) bool {
	return strings.HasSuffix(file.Name(), "_test.go")
}
