package signature_test

import (
	"go/ast"
	"go/parser"
	"go/token"
	"go/types"
	"testing"

	"golang.org/x/tools/go/analysis"
	"golang.org/x/tools/go/analysis/analysistest"
	"golang.org/x/tools/go/analysis/passes/inspect"
	"golang.org/x/tools/go/ast/inspector"

	"github.com/JacobJNilsson/anti-slop-go/internal/signature"
)

// probe is a test-only analyzer. It reports every parameter of the
// empty interface type that the shared tests do not accept, so one run
// drives the whole package the way rules G03 and G04 drive it. The
// package holds no knowledge of parameters against results, so the
// parameter side alone reaches every path.
var probe = &analysis.Analyzer{
	Name:     "probe",
	Doc:      "report empty interface parameters that no contract accepts",
	Requires: []*analysis.Analyzer{inspect.Analyzer},
	Run:      probeRun,
}

// CONTRACT: analysis.Analyzer.Run fixes this signature.
func probeRun(pass *analysis.Pass) (any, error) {
	// SAFETY: inspect.Analyzer is in Requires, so the driver always
	// supplies its result, and that result is an *inspector.Inspector.
	insp := pass.ResultOf[inspect.Analyzer].(*inspector.Inspector)

	contracts := signature.NewContracts(pass)

	insp.WithStack([]ast.Node{(*ast.FuncType)(nil)}, func(n ast.Node, push bool, stack []ast.Node) bool {
		if !push {
			return true
		}
		// SAFETY: the node filter above admits this type only.
		sig := n.(*ast.FuncType)
		if contracts.Generated(sig.Pos()) {
			return true
		}
		parent := stack[len(stack)-2]

		index := 0
		for _, field := range sig.Params.List {
			start, span := index, signature.NameCount(field)
			index += span
			if !signature.IsEmptyInterface(pass.TypesInfo.TypeOf(field.Type)) {
				continue
			}
			if contracts.Justified(stack) {
				return true
			}
			if contracts.Implements(parent, func(declared *types.Signature) bool {
				return declaresEmpty(declared, start, span)
			}) {
				continue
			}
			pass.Reportf(field.Type.Pos(), "parameter uses the empty interface")
		}
		return true
	})
	return nil, nil
}

// declaresEmpty reports whether declared holds the empty interface at
// every parameter from start to start+span.
func declaresEmpty(declared *types.Signature, start, span int) bool {
	if declared == nil || start+span > declared.Params().Len() {
		return false
	}
	for i := start; i < start+span; i++ {
		if !signature.IsEmptyInterface(declared.Params().At(i).Type()) {
			return false
		}
	}
	return true
}

func TestContracts(t *testing.T) {
	analysistest.Run(t, analysistest.TestData(), probe, "a")
}

// The generated-file test is the one test every rule uses, and a rule
// without a marker takes it alone. This test drives that entry point
// directly, because a fixture of one rule cannot pin it for the others.
func TestGeneratedFiles(t *testing.T) {
	const generatedSrc = "// Code generated by a fake tool. DO NOT EDIT.\n\npackage p\n\nvar g = 1\n"
	const handWrittenSrc = "package p\n\nvar h = 1\n"

	fset := token.NewFileSet()
	generated := parse(t, fset, "generated.go", generatedSrc)
	handWritten := parse(t, fset, "hand_written.go", handWrittenSrc)

	pass := &analysis.Pass{Fset: fset, Files: []*ast.File{generated, handWritten}}
	isGenerated := signature.GeneratedFiles(pass)

	if !isGenerated(generated.Pos()) {
		t.Error("GeneratedFiles rejected a file with the generated header")
	}
	if isGenerated(handWritten.Pos()) {
		t.Error("GeneratedFiles accepted a hand-written file")
	}
}

// TestGeneratedFilesReadsTheAcceptedHeaderForms pins the marker text
// and the marker window that 003 states. The accepted text comes from
// the lax matcher of golangci-lint. The window comes from go/ast: a
// comment counts only above the package clause.
//
// The table holds the four markers, the boundary of the window, and the
// text the module refuses. Each case is one file, so one entry cannot
// hide behind another.
//
// Three rows carry a measurement of 003. A marker below a license
// header or below a build constraint still counts, because one
// generator writes both layouts. A package doc that describes generated
// code counts as well, which is the surface 003 states.
func TestGeneratedFilesReadsTheAcceptedHeaderForms(t *testing.T) {
	tests := []struct {
		name string
		src  string
		want bool
	}{
		{
			"the canonical header of go/ast",
			"// Code generated by a fake tool. DO NOT EDIT.\n\npackage p\n\nvar g = 1\n",
			true,
		},
		{
			"the header of an in-house identifier generator",
			"// Generated file, do not edit.\n// Generated by an in-house tool.\n\npackage p\n\nvar g = 1\n",
			true,
		},
		{
			"a code generated marker with no do not edit line",
			"// code generated by a fake tool\n\npackage p\n\nvar g = 1\n",
			true,
		},
		{
			"the autogenerated file marker of easyjson",
			"// AUTOGENERATED FILE: easyjson marshaler/unmarshalers.\n\npackage p\n\nvar g = 1\n",
			true,
		},
		{
			"the block header of swagger codegen",
			"/*\n * Fake API\n *\n * Generated by: Swagger Codegen (https://example.test).\n */\n\npackage p\n\nvar g = 1\n",
			true,
		},
		{
			"a marker of any letter case",
			"// DO NOT EDIT.\n\npackage p\n\nvar g = 1\n",
			true,
		},
		{
			"a marker after the package clause",
			"package p\n\n// Generated file, do not edit.\nvar g = 1\n",
			false,
		},
		{
			"a marker that trails the package clause",
			"package p // Generated file, do not edit.\n\nvar g = 1\n",
			false,
		},
		{
			"a marker in the doc comment of a function",
			"package p\n\n// Do not edit this function by hand.\nfunc F() {}\n",
			false,
		},
		{
			"the word generated in an ordinary header sentence",
			"// A tool generated the grammar that this parser reads.\n\npackage p\n\nvar g = 1\n",
			false,
		},
		{
			"a header that holds a marker inside a sentence",
			"// The code generated for the API lives in another package.\n\npackage p\n\nvar g = 1\n",
			true,
		},
		{
			"a block comment that holds a marker",
			"/* Generated file, do not edit. */\n\npackage p\n\nvar g = 1\n",
			true,
		},
		{
			"a canonical marker below a license header",
			"// Copyright 2018 The Authors.\n// A BSD-style license governs this source code.\n\n" +
				"// Code generated by protoc-gen-go. DO NOT EDIT.\n\npackage p\n\nvar g = 1\n",
			true,
		},
		{
			"a lax marker below a license and a build constraint",
			"// SPDX-License-Identifier: BSD-3-Clause\n//go:build linux && ppc64\n\n" +
				"// Created by cgo -godefs - DO NOT EDIT\n// cgo -godefs types_linux.go\n\npackage p\n\nvar g = 1\n",
			true,
		},
		{
			"a package doc that describes generated code",
			"// Package p wraps the code generated by X.\npackage p\n\nvar g = 1\n",
			true,
		},
		{
			"a header of build directives only",
			"//go:build linux\n\npackage p\n\nvar g = 1\n",
			false,
		},
		{
			"a hand-written file with no comment",
			"package p\n\nvar h = 1\n",
			false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			fset := token.NewFileSet()
			file := parse(t, fset, "p.go", tt.src)
			pass := &analysis.Pass{Fset: fset, Files: []*ast.File{file}}

			if got := signature.GeneratedFiles(pass)(file.Pos()); got != tt.want {
				t.Errorf("GeneratedFiles = %v, want %v", got, tt.want)
			}
		})
	}
}

// parse returns the syntax of one source file, with its comments.
func parse(t *testing.T, fset *token.FileSet, name, src string) *ast.File {
	t.Helper()
	file, err := parser.ParseFile(fset, name, src, parser.ParseComments)
	if err != nil {
		t.Fatalf("the fixture source %s does not parse: %v", name, err)
	}
	return file
}

// The test-file test reads the name of the file, which is the test the
// go tool applies. Two rules read test code, so the test lives here.
func TestIsTestFile(t *testing.T) {
	tests := []struct {
		name string
		want bool
	}{
		{"a_test.go", true},
		{"a.go", false},
		{"testdata.go", false},
		{"_test.go", true},
		{"a_test.go.bak", false},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			fset := token.NewFileSet()
			file := fset.AddFile(tt.name, -1, 1)
			if got := signature.IsTestFile(file); got != tt.want {
				t.Errorf("IsTestFile(%q) = %v, want %v", tt.name, got, tt.want)
			}
		})
	}
}
