// Code generated by a fake tool. DO NOT EDIT.

package a

import (
	"testing"

	"github.com/stretchr/testify/require"
)

// Nobody edits a generated file to change the form of its assertions,
// so a report here has no reader who can act on it.
func TestGenerated(t *testing.T) {
	got := build()
	require.Equal(t, "boot", got.Name)
	require.Equal(t, 3, got.Count)
}
