// Code generated by a fake tool. DO NOT EDIT.

package a

func GeneratedChain(u User) User {
	return any(u).(User)
}

func GeneratedBinding(u User) User {
	v := any(u)
	return v.(User)
}

// A generator such as goyacc points the reader back at its input with
// a //line directive. The directive changes the name that
// token.Position reports, but the file is still generated, so nothing
// below is reported.
//line grammar.y:42

func GeneratedChainAfterLine(u User) User {
	return any(u).(User)
}
