// Code generated by a fake tool. DO NOT EDIT.

package a

func GeneratedAssert(err error) int {
	return err.(*ParseError).Line
}

func GeneratedSwitch(err error) int {
	switch e := err.(type) {
	case *ParseError:
		return e.Line
	}
	return 0
}

// A generator such as goyacc points the reader back at its input with
// a //line directive. The directive changes the name that
// token.Position reports, but the file is still generated, so nothing
// below is reported.
//line grammar.y:42

func GeneratedAssertAfterLine(err error) int {
	return err.(*ParseError).Line
}
