// Code generated by a fake tool. DO NOT EDIT.

package a

func GeneratedSwitch(v any) string {
	switch v.(type) {
	case int:
		return "int"
	}

	return ""
}

// A generator such as goyacc points the reader back at its input with a
// //line directive. The directive changes the name that token.Position
// reports, but the file is still generated, so nothing below is
// reported.
//line grammar.y:42

func GeneratedSwitchAfterLine(v any) string {
	switch v.(type) {
	case string:
		return "string"
	}

	return ""
}
