// Code generated by a fake tool. DO NOT EDIT.

package a

import (
	"testing"

	"github.com/stretchr/testify/require"
)

// Nobody edits a generated file to bind a value to a variable, so a
// report here has no reader who can act on it.
func TestGenerated(t *testing.T) {
	require.Equal(t, buildItem("boot"), storedRoutes(t, "boot"))
}
