// Code generated by a fake tool. DO NOT EDIT.

package a

func GeneratedParam(v any) {}

// A generator such as goyacc points the reader back at its input with a
// //line directive. The directive changes the name that token.Position
// reports, but the file is still generated, so nothing below is
// reported.
//line grammar.y:42

func GeneratedAfterLine(v any) {}
