// Code generated by the fixture writer. DO NOT EDIT.

package a

import (
	"strings"
	"testing"
)

// A generated test file gets no report. Nobody edits such a file to
// rewrite an assertion.
func TestGeneratedFile(t *testing.T) {
	if strings.Contains(Seed("").Error(), "run id") {
		t.Error("Seed(\"\") reported the run id error")
	}
}
