// Code generated by a fake tool. DO NOT EDIT.

package a

import (
	_ "bou.ke/monkey"
	_ "unsafe"
)

//go:linkname generatedLink a.generated
func generatedLink()

// generatedPatch rewires the package from a generated test file. A
// program writes the file, so a report has no reader who can act on
// it.
func generatedPatch() {
	send = func(message string) error { return nil }
}
